apiVersion: apps/v1
kind: Deployment
metadata:
  name: migration-proxy
  namespace: aibang-1111111111-bbdm
  labels:
    app: migration-proxy
    component: proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: migration-proxy
      component: proxy
  template:
    metadata:
      labels:
        app: migration-proxy
        component: proxy
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 8080
          name: health
          protocol: TCP
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        - name: nginx-logs
          mountPath: /var/log/nginx
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        
        # Resource limits
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        
        # Security context
        securityContext:
          runAsNonRoot: true
          runAsUser: 101
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      
      volumes:
      - name: nginx-config
        configMap:
          name: migration-proxy-config
          items:
          - key: nginx.conf
            path: nginx.conf
      - name: nginx-logs
        emptyDir: {}
      
      # Pod security and scheduling
      securityContext:
        fsGroup: 101
      
      # Anti-affinity to spread pods across nodes
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - migration-proxy
              topologyKey: kubernetes.io/hostname