apiVersion: v1
kind: ConfigMap
metadata:
  name: migration-proxy-config
  namespace: aibang-1111111111-bbdm
  labels:
    app: migration-proxy
    component: config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        
        # Log format for monitoring
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                       '$status $body_bytes_sent "$http_referer" '
                       '"$http_user_agent" "$http_x_forwarded_for" '
                       'upstream_addr="$upstream_addr" '
                       'upstream_response_time="$upstream_response_time" '
                       'request_time="$request_time"';
        
        access_log /var/log/nginx/access.log main;
        error_log /var/log/nginx/error.log warn;
        
        # Upstream definitions
        upstream old_cluster_backend {
            server bbdm-api.aibang-1111111111-bbdm.svc.cluster.local:8078;
            keepalive 32;
        }
        
        upstream new_cluster_backend {
            server api-name01.kong.dev.aliyun.intracloud.cn.aibang:443;
            keepalive 32;
        }
        
        # Health check endpoint
        server {
            listen 8080;
            server_name _;
            
            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }
            
            location /ready {
                access_log off;
                # Check if upstream is available
                proxy_pass http://old_cluster_backend/health;
                proxy_connect_timeout 1s;
                proxy_read_timeout 1s;
                proxy_send_timeout 1s;
            }
        }
        
        # Main proxy server
        server {
            listen 80;
            server_name api-name01.teamname.dev.aliyun.intracloud.cn.aibang;
            
            # Proxy settings
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Timeout settings
            proxy_connect_timeout 30s;
            proxy_send_timeout 30s;
            proxy_read_timeout 30s;
            
            # Buffer settings
            proxy_buffering on;
            proxy_buffer_size 4k;
            proxy_buffers 8 4k;
            
            location / {
                # Default to old cluster for now (migration_percentage = 0)
                # This will be enhanced in later tasks for gradual migration
                proxy_pass http://old_cluster_backend;
                
                # Error handling - fallback to old cluster if new cluster fails
                proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
            }
        }
    }