apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: migration-proxy
  namespace: aibang-1111111111-bbdm
  labels:
    app: migration-proxy
    component: monitoring
spec:
  selector:
    matchLabels:
      app: migration-proxy
      component: service
  endpoints:
  - port: health
    path: /health
    interval: 30s
    scrapeTimeout: 10s