apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"busybox-app","namespace":"lex-ext-kdp"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"busybox-app"}},"template":{"metadata":{"labels":{"app":"busybox-app","kdp":"lex-ext-kdp","sms":"enabled"}},"spec":{"containers":[{"args":["/bin/sh","-c","sleep 10; touch /tmp/healthy; sleep 30000"],"image":"busybox:latest","name":"busybox-app","readinessProbe":{"exec":{"command":["cat","/tmp/healthy"]},"initialDelaySeconds":10,"periodSeconds":5}}]}}}}
  creationTimestamp: "2022-05-28T02:54:21Z"
  generation: 2
  name: busybox-app
  namespace: lex
  resourceVersion: "759996"
  uid: d302028a-e48e-4c1a-a0e1-6b3193e9c49e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: busybox-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: busybox-app
        kdp: lex-ext-kdp
        sms: enabled
    spec:
      containers:
        - args:
            - /bin/sh
            - -c
            - sleep 10; touch /tmp/healthy; sleep 30000
          image: busybox:latest
          imagePullPolicy: Always
          name: busybox-app
          readinessProbe:
            exec:
              command:
                - cat
                - /tmp/healthy
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2022-05-28T02:54:21Z"
      lastUpdateTime: "2022-05-28T02:55:05Z"
      message: ReplicaSet "busybox-app-744479c67d" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2022-06-11T21:37:09Z"
      lastUpdateTime: "2022-06-11T21:37:09Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
