apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: nginx-app-2
  namespace: lex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - image: nginx:latest
          imagePullPolicy: Always
          name: nginx-app
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
