apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager-demo-ksa
  namespace: default
  annotations:
    # This annotation binds the KSA to the GSA via Workload Identity
    iam.gke.io/gcp-service-account: secret-manager-demo-gsa@PROJECT_ID.iam.gserviceaccount.com
  labels:
    app: secret-manager-demo
    component: service-account
---
# Optional: Create a dedicated namespace for the application
apiVersion: v1
kind: Namespace
metadata:
  name: secret-manager-demo
  labels:
    name: secret-manager-demo
---
# Service Account in the dedicated namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager-demo-ksa
  namespace: secret-manager-demo
  annotations:
    iam.gke.io/gcp-service-account: secret-manager-demo-gsa@PROJECT_ID.iam.gserviceaccount.com
  labels:
    app: secret-manager-demo
    component: service-account