apiVersion: v1
kind: Service
metadata:
  name: timeout-app-service
  labels:
    app: timeout-app
spec:
  selector:
    app: timeout-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer