# Multi-user Trust Config for mTLS
# Each user's certificates are organized under their own section
# Format: YAML with user identification and certificate information

users:
  - user_id: "user-a"
    name: "Customer A"
    created_at: "2024-01-10T10:00:00Z"
    certificates:
      root_ca:
        name: "customer-a-root"
        fingerprint: "SHA256:a1b2c3d4e5f6..."  # SHA-256 fingerprint
        pem: |
          -----BEGIN CERTIFICATE-----
          MIIDdzCCAl+gAwIBAgIE...
          -----END CERTIFICATE-----
      intermediate_ca:
        name: "customer-a-intermediate"
        fingerprint: "SHA256:f6e5d4c3b2a1..."  # SHA-256 fingerprint
        pem: |
          -----BEGIN CERTIFICATE-----
          MIIDXTCCAkWgAwIBAgIJ...
          -----END CERTIFICATE-----
  
  - user_id: "user-b"
    name: "Customer B"
    created_at: "2024-01-11T14:30:00Z"
    certificates:
      root_ca:
        name: "customer-b-root"
        fingerprint: "SHA256:1a2b3c4d5e6f..."  # SHA-256 fingerprint
        pem: |
          -----BEGIN CERTIFICATE-----
          MIIDdzCCAl+gAwIBAgIE...
          -----END CERTIFICATE-----
      intermediate_ca:
        name: "customer-b-intermediate"
        fingerprint: "SHA256:6f5e4d3c2b1a..."  # SHA-256 fingerprint
        pem: |
          -----BEGIN CERTIFICATE-----
          MIIDXTCCAkWgAwIBAgIJ...
          -----END CERTIFICATE-----

# Metadata
metadata:
  version: "1.0"
  last_updated: "2024-01-11T14:30:00Z"
  environment: "production"  # dev, staging, prod