apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: psc-demo
  labels:
    app: db-app
    component: credentials
type: Opaque
data:
  # 数据库密码 (base64 编码)
  # 实际部署时需要替换为真实的 base64 编码密码
  DB_PASSWORD: QXBwVXNlclBhc3N3b3JkMTIzIQ==  # AppUserPassword123!
  
  # 可选：数据库连接字符串
  # DB_CONNECTION_STRING: 将在部署脚本中生成