apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-app-sa
  namespace: psc-demo
  annotations:
    # Workload Identity 绑定
    iam.gke.io/gcp-service-account: db-app-gsa@PROJECT_ID.iam.gserviceaccount.com
  labels:
    app: db-app
    component: service-account