apiVersion: v1
data:
  password: cmVkaXNwYXNzd29yZDEyMw==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"password":"cmVkaXNwYXNzd29yZDEyMw=="},"kind":"Secret","metadata":{"annotations":{},"name":"redis-secrets","namespace":"lex"},"type":"Opaque"}
  name: redis-secrets
  namespace: lex
type: Opaque
