apiVersion: v1
kind: Service
metadata:
  name: api-name01-kong-dev
  namespace: default
spec:
  type: ExternalName
  externalName: api-name01.kong.dev.aliyun.intracloud.cn.aibang
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
---
# 如果需要指定具体 IP，使用这种方式
apiVersion: v1
kind: Service
metadata:
  name: api-name01-kong-dev-ip
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: api-name01-kong-dev-ip
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.1.100 # 替换为实际的 IP 地址
    ports:
      - name: http
        port: 80
        protocol: TCP
      - name: https
        port: 443
        protocol: TCP
